from .bod_api import Client

client = Client()

bod = client.fias.get_database('BoD')
bod_users = client.fias.get_database('BoD_users')

addhousetypes = bod.get_collection('addhousetypes')
addrobj = bod.get_collection('addrobj')
addrobjdivision = bod.get_collection('addrobjdivision')
addrobjparams = bod.get_collection('addrobjparams')
addrobjtypes = bod.get_collection('addrobjtypes')
admhierarchy = bod.get_collection('admhierarchy')
apartments = bod.get_collection('apartments')
apartmentsparams = bod.get_collection('apartmentsparams')
apartmenttypes = bod.get_collection('apartmenttypes')
carplaces = bod.get_collection('carplaces')
carplacesparams = bod.get_collection('carplacesparams')
changehistory = bod.get_collection('changehistory')
houses = bod.get_collection('houses')
housesparams = bod.get_collection('housesparams')
housetypes = bod.get_collection('housetypes')
munhierarchy = bod.get_collection('munhierarchy')
normativedocs = bod.get_collection('normativedocs')
normativedocskinds = bod.get_collection('normativedocskinds')
normativedocstypes = bod.get_collection('normativedocstypes')
objectlevels = bod.get_collection('objectlevels')
operationtypes = bod.get_collection('operationtypes')
paramtypes = bod.get_collection('paramtypes')
reestrobjects = bod.get_collection('reestrobjects')
rooms = bod.get_collection('rooms')
roomsparams = bod.get_collection('roomsparams')
roomtypes = bod.get_collection('roomtypes')
steads = bod.get_collection('steads')
steadsparams = bod.get_collection('steadsparams')
